### ISSUE TITLE
How can i fix this error?

### ISSUE THREAD

**Issue by sajedulsakib001** [mohamadayash22/flutter-movie-app#1]
![Screenshot 2023-09-03 164142](https://github.com/mohamadayash22/flutter-movie-app/assets/48612479/fb8dbac7-87a2-4c73-9799-555f59375ad3)

**Comment by mohamadayash22** [comment]
Thank you for reporting this issue.
Flutter has now adopted the "SearchBar" name for one of its built-in widgets. To resolve this, you only need to rename your widget. I've already taken care of this and committed the required changes.
