### ISSUE TITLE
AI movie recommendations based on favorite movies

### ISSUE THREAD

**Issue by th8m0z** [mohamadayash22/flutter-movie-app#5]
If this project is still actively maintained, I'd love to add a feature where users can input their favorite movies and embeddings are used to find similar movies that they will probably like.

Would appreciate your response, just let me know and I'll get to work.

**Comment by mohamadayash22** [comment]
Hi @th8m0z

Thank you so much for suggesting this awesome feature! I really appreciate your interest in making the project even better.

While I love the idea, I'm currently focusing on other web development projects and won't be working on this one anymore.
